# Generated by Django 6.0.1 on 2026-06-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admins',
        ),
    ]
