# Generated by Django 6.0.1 on 2026-06-10 21:07

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=dashboard.models.dashboard_upload_to)),
            ],
        ),
    ]
